### ISSUE TITLE
Meta: Write README and rename repo?

### ISSUE THREAD

**Issue by akien-mga** [securas/Daemon-vs-Demon#12]
The README.md is currently quite empty, it would be nice to add a proper description of the game, screenshot/gif and link to the itch.io page.

It might also be worth renaming the GitHub repository (the previous name will stick work as a redirection) to better reflect what it is about? (e.g. `daemon-vs-demon` or `gameoff-2017`)

**Comment by securas** [comment]
thanks for taking the initiative on this!
