### ISSUE TITLE
Be more explicit about the licensing

### ISSUE THREAD

**Issue by akien-mga** [securas/Daemon-vs-Demon#14]
The itch.io page mentions:

> In the spirit of the GitHub Game Off Jam, the game and graphical assets are freely available here: https://github.com/securas/goj with a very permissible MIT license. Also, the music and sfx are available under a CC license.

Mentioning only "a CC license" does not mean much, and likely does not fulfill the requirements of said CC license. The license can be CC-BY 3.0, CC-BY-SA 4.0, CC-BY-ND 4.0, CC0, etc.

Based on the exact license flavour, you might have to give attribution to the author (BY), typically done by mentioning their name and linking to the page where they distribute the asset. The version number is also meaningful, as those are legal texts and the versions differ even for a same combination of parameters (BY, SA, NC, ND).

- For the character sprites by svh440, it seems to be CC-BY-NC judging by https://i.imgur.com/RFKVq.png, though the version is not specified (but that's better than just CC).
- For the music and sfx, I don't find much on the link you provide to the artist's soundcloud
- For your own work, it would be nice to specify a name in the copyright statement of the MIT license (after `(C) 2017`).

**Comment by securas** [comment]
Still trying to figure out if and how we can have multiple licenses on the assets. Mundusnine composed the music and created all the sounds specifically for this demo but those are to be one of the CC whereas everything else that we made is MIT.

**Comment by akien-mga** [comment]
Sure, you can have multiple/different licenses for the assets. You just need the author to decide on one, and document it somewhere, e.g.:
"Sounds effects and music tracks in `gameoffgame/assets/Sound` are licensed under CC-BY 4.0 International by Mundusnine <link>".

**Comment by securas** [comment]
thanks for your feedback... I'm trying to update these asap.
