### ISSUE TITLE
Intro: You can invoke the sword before you're given one

### ISSUE THREAD

**Issue by akien-mga** [securas/Daemon-vs-Demon#5]
First of all congrats for this game, it's very cool :D

After the first cutscene in hell, you are sent to the graveyard without any weapon, and the story is that you should get slaughtered, back to hell where the imp gives you a sword.

But if you press K while in the graveyard unarmed, you get your sword with a blood splatter animation, so the story no longer works :)

**Comment by securas** [comment]
Cheers! And thank you for the comments!
Adding the "K" option to transform back was a last minute addition... And it's broken since the player always transforms back to his "sword" form.

**Comment by securas** [comment]
fixed!
