### ISSUE TITLE
Font does not distinguish between M and N

### ISSUE THREAD

**Issue by akien-mga** [securas/Daemon-vs-Demon#8]
The low-res font used is nice overall, but the fact that it uses the same glyph for M and N makes it actually quite hard to read:
![spectacle tj4969](https://user-images.githubusercontent.com/4701338/33809596-b6c758cc-ddf9-11e7-8d17-d2005d223087.png)
For example it's impossible to know how you tester is named from how it's displayed :)

**Comment by securas** [comment]
True... I need to re-design the font quite a bit.

**Comment by securas** [comment]
Modified font.
